theme: jekyll-theme-minimal

title: Microsoft Health Architectures 
description: Provide reference architectures and, when appropriate, implementations

logo: /assets/images/logo.png

url: https://microsoft.github.io/health-architectures/
