theme: jekyll-theme-minimal

title: Microsoft Health Architectures 
description: Provide reference architectures and, when appropriate, implementations

logo: /assets/images/logo.png

source: /health-architectures/

include: /health-architectures/_posts
