theme: jekyll-theme-minimal

title: Microsoft Health Architectures 
description: Provide reference architectures and, when appropriate, implementations

baseurl: /health-architectures

logo: /assets/images/logo.png

include: /health-architectures/_posts
