theme: jekyll-theme-minimal

title: Microsoft Health Architectures 
description: Reference architectures and, where appropriate, implementations

logo: /assets/images/logo.png

include: /_posts

baseurl: /health-architectures

defaults:
  - scope:
      path: "/health-architectures/assets/images"
    values:
      image: true
      author: Health-Architectures
